Quick attempt at fixing EOF error issue encountered on linux/ARM
jacobsa/daemonize pull request #1
Opened 2017-03-09 09:44 UTC by elProxy

When trying to run gcfuse on linux/ARM, ran into the issue described
here:
https://github.com/GoogleCloudPlatform/gcsfuse/issues/197

Change the API slightly (expose even less), and switch to using a local
unix socket (assuming windows is not a primary target for gcsfuse) for
communicating back status to the parent process.

2017-03-09 23:27 UTC, jacobsa commented
Thanks for this. Can you describe here and in your commit message what the problem was?

2017-04-04 14:21 UTC, elProxy commented
Well, unfortunately I didn't really dig too deep into why things didn't work, I noticed that things ran fine with --foreground and proceeded to just make this last bit work for me by simply using a unix socket as it feels a bit more flexible for that sort of non performance-critical IPC anyway. Though it's interesting that the other report also happened to be on ARM.

2017-04-05 00:11 UTC, jacobsa requested changes
Sending comments on specifics, but I'm not sure I'm comfortable with making this change without knowing why (and therefore whether) it fixed the root cause of the bug.

2017-04-05 00:11 UTC, jacobsa commented on daemonize.go
> +// This package provides the convenience for writing a tool that spins itself
Why change the wording here?

2017-04-05 00:11 UTC, jacobsa commented on daemonize.go
> +	// TODO: drop osext dependency once minmum required go verison is 1.8
Please just do this now. Those binaries that need to build with older versions of Go can vendor an old version.

2017-04-05 00:11 UTC, jacobsa commented on daemonize.go
> -// For use by the daemon: the writer that should be used for logging status
Why did you remove this feature?

2018-11-05 17:46 UTC, kazazes commented
This is still a blocking issue on ARM builds.

```
$ go get -u github.com/googlecloudplatform/gcsfuse
# github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/fuse/internal/buffer
./runtime.go:24: missing function body for "memclr"
./runtime.go:24: missing function body for "memmove"
```

2020-10-20 07:29 UTC, closed without merging